# Standard Config file for MPET solver

solver_settings:
  log_level : 20
  T : 3.0
  num_T_steps : 100
  num_networks : 3
  element_type : CG
  

material_parameters:
  E : 1500 # Pa, Young modulus
  nu : 0.49 # Poisson ratio
  rho : 1081 #m³/kg, Density of tissue
  kappa : 
    - 1.0e-14 #m² Permeability fluid 1
    - 1.0e-14 #m² Permeability fluid 2
    - 1.0e-14 #m² Permeability fluid 3
  alpha :
    - 0.5 #Biot-Willis coefficient fluid 1
    - 0.49 #Biot-Willis coefficient fluid 2
    - 0.01 #Biot-Willis coefficient fluid 3
  c :
    - 10.0e-6 #Storage coefficient fluid 1
    - 10.0e-6 #Storage coefficient fluid 2
    - 10.0e-6 #Storage coefficient fluid 3
  mu_f :
    - 0.7e-3 #Viscosity fluid 1
    - 0.7e-3 #Viscosity fluid 2
    - 0.7e-3 #Viscosity fluid 3
  p_initial :
    - 0.0 #Initial pressure network 1
    - 0.0 #Initial pressure network 2
    - 0.0 #Initial pressure network 3

boundary_parameters:
  Compliance : 2.5 # [microL/mmHg]
  Resistance : 10.81 # [mmHg*min/microL]
  beta_sas : 1.0e-5
  beta_ven : 1.0e-5
  p_ven_initial : 0.0
  p_sas_initial : 0.0

source_data:
  source_file : data/baladont_tot_inflow_series_shifted.csv
  source_params:
    f : 1.0
  scaling : 1.0e-9 ## mm^3 to m^3
  scale_by_total_vol : True
spinal_outlet:
  outlet_expression : "-P0*pow(10, outflow_vol / PVI)"
  outlet_params :
    PVI : 10.0e-6 # https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3221868/, 30 ml
initial_pressure : 600
